### ISSUE TITLE
Make case-insensitive

### ISSUE THREAD

**Issue by jgard** [TastefulElk/iam-legend#69]
Many parts of IAM policies are _not_ case sensitive.  Like [action names](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_action.html#:~:text=The%20prefix%20and%20the%20action%20name%20are%20case%20insensitive.) and [condition context keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html#:~:text=Context%20key%20names%20are%20not%20case%2Dsensitive.).  However it appears iam-legend only provides mouseover information if the action name matches the casing of the API definitions:
Works:
![image](https://github.com/TastefulElk/iam-legend/assets/46004534/d116d92f-7eb0-4733-9e31-657fbdbe4f41)

Doesn't work with different-cased service prefix, doesn't recognize it as an IAM action to consider:
![image](https://github.com/TastefulElk/iam-legend/assets/46004534/794969c6-8c1b-4059-8b12-67bf8ef13788)

Doesn't work with different-cased action, but at least recognizes this is an IAM service:
![image](https://github.com/TastefulElk/iam-legend/assets/46004534/0a78f778-659f-40f8-9587-e2cd08695dcc)

I think the extension should be case-insensitive in these situations.  Thanks!

**Comment by TastefulElk** [comment]
You're of course correct and this has now been fixed. Thanks for reporting it @jgard!
